export const POST_KANBAN_START = 'POST_KANBAN_START';
export const POST_KANBAN_SUCCEED = 'POST_KANBAN_SUCCEED';
export const POST_KANBAN_FAIL = 'POST_KANBAN_FAIL'; 

export const GET_KANBAN_START = 'GET_KANBAN_START';
export const GET_KANBAN_SUCCEED = 'GET_KANBAN_SUCCEED';
export const GET_KANBAN_FAIL = 'GET_KANBAN_FAIL'; 

export const DELETE_KANBAN_START = 'DELETE_KANBAN_START';
export const DELETE_KANBAN_SUCCEED = 'DELETE_KANBAN_SUCCEED';
export const DELETE_KANBAN_FAIL = 'DELETE_KANBAN_FAIL'; 

export const POST_TASKCARD_START = 'POST_TASKCARD_START';
export const POST_TASKCARD_SUCCEED = 'POST_TASKCARD_SUCCEED';
export const POST_TASKCARD_FAIL = 'POST_TASKCARD_FAIL'; 

export const PUT_TASKCARD_START = 'PUT_TASKCARD_START';
export const PUT_TASKCARD_SUCCEED = 'PUT_TASKCARD_SUCCEED';
export const PUT_TASKCARD_FAIL = 'PUT_TASKCARD_FAIL'; 