export const GET_PROJECT_START = 'GET_PROJECT_START';
export const GET_PROJECT_SUCCEED = 'GET_PROJECT_SUCCEED';
export const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL';

export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_DELETE = 'PROJECT_DELETE';
